<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Admission</name>
   <tag></tag>
   <elementGuidId>a09a98e2-b819-4ff2-84e6-6291a8df2990</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mega-menu-item-892 > a.mega-menu-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mega-menu-item-892']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6e134d30-23b4-48f2-bf42-d1de38bbf25f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mega-menu-link</value>
      <webElementGuid>f4502a8a-d72a-4cab-8338-afba61714454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://earthwp.magicmindtechnologies.com/dominion-latest-wp/?page_id=12</value>
      <webElementGuid>1cab55d6-2025-4f46-8013-b9f5d7658c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admission</value>
      <webElementGuid>4d217ae1-d4d5-4cde-8f29-76f4b38c63f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mega-menu-item-892&quot;)/a[@class=&quot;mega-menu-link&quot;]</value>
      <webElementGuid>9893ad75-8efc-414e-851f-6d140f975804</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='mega-menu-item-892']/a</value>
      <webElementGuid>096e0558-f6fd-4941-b768-b387442d5157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Admission')])[2]</value>
      <webElementGuid>2c416881-6b15-4a67-8ca2-6da45d96e121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For Teachers'])[1]/following::a[1]</value>
      <webElementGuid>95852614-c565-4930-995e-47b2575861b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomination'])[1]/following::a[2]</value>
      <webElementGuid>140c0989-097a-4fcf-9be5-30892e4e2a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Teacher Application'])[1]/preceding::a[1]</value>
      <webElementGuid>b486ff09-dfc7-4bb1-8f0e-1de2835fda08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomination'])[2]/preceding::a[2]</value>
      <webElementGuid>780d61fc-e89e-4673-b4b2-f3bf95eb4aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[@href='http://earthwp.magicmindtechnologies.com/dominion-latest-wp/?page_id=12'])[2]</value>
      <webElementGuid>3750344f-2065-4afe-b02e-e32a01e450b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li/a</value>
      <webElementGuid>83489128-bba3-40a1-9862-7735ec1ea08f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://earthwp.magicmindtechnologies.com/dominion-latest-wp/?page_id=12' and (text() = 'Admission' or . = 'Admission')]</value>
      <webElementGuid>a86f5fd3-7d81-4cf2-921e-d575c7ea4a6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
