<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Curriculum  Methods</name>
   <tag></tag>
   <elementGuidId>b8d8f7cc-2337-48f5-96c3-894b4dba104d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mega-menu-item-406 > a.mega-menu-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mega-menu-item-406']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>87a2e602-da1e-48ff-ae65-60458d7b09cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mega-menu-link</value>
      <webElementGuid>0f972e04-bcf1-486a-bb3d-c1757745f05e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://earthwp.magicmindtechnologies.com/dominion-latest-wp/?page_id=228</value>
      <webElementGuid>cb87eb0e-9c2f-4e5e-b57a-b10c895095d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d6346dc2-63ed-4541-8a5f-fc4ef861c468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Curriculum &amp; Methods</value>
      <webElementGuid>270713ac-77e8-4075-95a5-35ca08c31e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mega-menu-item-406&quot;)/a[@class=&quot;mega-menu-link&quot;]</value>
      <webElementGuid>128d445c-0c2e-412c-adb3-a3704243af8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='mega-menu-item-406']/a</value>
      <webElementGuid>1b43b6ac-1afa-4f21-9437-2fb9da8512d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Curriculum &amp; Methods')]</value>
      <webElementGuid>2c8cd59c-af94-4621-a13a-10af8c209c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomination'])[2]/following::a[1]</value>
      <webElementGuid>aeb72b8d-ffc2-46b1-b637-3c75ad498d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Teacher Application'])[1]/following::a[2]</value>
      <webElementGuid>c2712aa8-04e7-4866-a1af-253d0bb37b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROCESS'])[1]/preceding::a[2]</value>
      <webElementGuid>8d86b0a5-86eb-4224-ae1b-8c9cd9209dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Curriculum &amp; Methods']/parent::*</value>
      <webElementGuid>f0ee78ea-86f2-4cef-a75e-6d31af98ad10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://earthwp.magicmindtechnologies.com/dominion-latest-wp/?page_id=228']</value>
      <webElementGuid>eccf09f8-67ea-4aef-9dfc-62dace10621e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>f6949e32-2261-41fb-89de-3511e5ee1d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://earthwp.magicmindtechnologies.com/dominion-latest-wp/?page_id=228' and (text() = 'Curriculum &amp; Methods' or . = 'Curriculum &amp; Methods')]</value>
      <webElementGuid>6fce1698-efdd-4d44-883a-e19f79a7372f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
