<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Download</name>
   <tag></tag>
   <elementGuidId>a9cf0fba-cd34-4872-aef6-1d4858c4d9e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.curriculum_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Download')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>db8a1ee4-7daa-4637-9dcc-235e69231daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://localhost/dominion_wp/wp-content/uploads/2023/01/Curriculum-Map-Winter-12-1-2022-1.pdf</value>
      <webElementGuid>71c581a5-e84c-4a8a-9919-bceb940702de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>46943e1f-0153-468d-9cc8-8bfb58c47ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>curriculum_btn</value>
      <webElementGuid>0ce00e9c-1ca7-4777-83d0-961d8f001fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener</value>
      <webElementGuid>f2031097-385d-4334-9902-09a352e2c2dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download</value>
      <webElementGuid>50946342-88ee-4952-9143-870d723ca95e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;parent-div light-mode curriculum-one&quot;]/section[@class=&quot;inner-page-section&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;col-xl-10 col-lg-11 col-md-9 section-text our-curriculum-text&quot;]/p[2]/a[@class=&quot;curriculum_btn&quot;]</value>
      <webElementGuid>d94e8f39-25f1-48ee-86c9-1a44dc1b74a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Download')]</value>
      <webElementGuid>8753fdfb-2ca8-4eec-a27f-543ec384a4a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our Curriculum Map'])[1]/following::a[1]</value>
      <webElementGuid>c972dc0b-565e-48b7-a5f2-6b27129fa7af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dr. Laila Sanguras'])[1]/following::a[3]</value>
      <webElementGuid>a1026024-a543-42a1-8ff5-2f2bd685c158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From 9th to 12th grade'])[1]/preceding::a[1]</value>
      <webElementGuid>e92ea36b-d648-4d80-8c1c-0e233d54ed32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download']/parent::*</value>
      <webElementGuid>64d67e64-4db0-4ebe-935a-35d8de1c0875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[@href='http://localhost/dominion_wp/wp-content/uploads/2023/01/Curriculum-Map-Winter-12-1-2022-1.pdf'])[2]</value>
      <webElementGuid>161f8693-00d8-4801-86d7-a4cfac19f863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/p[2]/a</value>
      <webElementGuid>f0df042d-69ed-4eba-ac24-47a083d59693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost/dominion_wp/wp-content/uploads/2023/01/Curriculum-Map-Winter-12-1-2022-1.pdf' and (text() = 'Download' or . = 'Download')]</value>
      <webElementGuid>849b83c6-7764-437b-84bd-32ed0771b294</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
