<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Our Story</name>
   <tag></tag>
   <elementGuidId>19417907-629a-435b-b938-b4ee86731c79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.mega-menu-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mega-menu-item-199']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b9b49757-db3c-4f79-a5c4-622fd6860ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mega-menu-link</value>
      <webElementGuid>4f8eeb69-0392-430b-88c3-953e12f5c6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://dominionprep.org/our-story</value>
      <webElementGuid>da997ba9-81a6-4fd6-a605-75d628c03c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>01a14a78-e7d2-4e96-9f1d-7dc8a190b66f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Our Story</value>
      <webElementGuid>2c999d1f-c50c-4735-aeb8-b41490b338fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mega-menu-item-199&quot;)/a[@class=&quot;mega-menu-link&quot;]</value>
      <webElementGuid>8b40d040-0f9c-4515-826d-dbb8843310c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='mega-menu-item-199']/a</value>
      <webElementGuid>97d3365f-0d03-45cb-8f91-dc17f62da22f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Our Story')]</value>
      <webElementGuid>df13820b-586e-477e-abc0-3d67db2f260c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For Parents'])[1]/preceding::a[1]</value>
      <webElementGuid>1bc259a4-7e1c-4e5f-a120-bc33dbd85072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admission'])[1]/preceding::a[2]</value>
      <webElementGuid>01a8aec9-2a17-4dfa-9e49-5b54a6d16a35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Our Story']/parent::*</value>
      <webElementGuid>435b2799-42dd-44b4-abb7-f9246bd12024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://dominionprep.org/our-story')]</value>
      <webElementGuid>4480699d-ee8a-4b86-b837-407c2098de02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>445c6d59-b710-46de-ad5d-0e77e9826c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://dominionprep.org/our-story' and (text() = 'Our Story' or . = 'Our Story')]</value>
      <webElementGuid>90741f52-5a23-4557-a19e-485ee5055722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://earthwp.magicmindtechnologies.com/dominion-latest-wp/?page_id=32']</value>
      <webElementGuid>6a61bb1b-fed7-482c-8fc5-223de314d197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://earthwp.magicmindtechnologies.com/dominion-latest-wp/?page_id=32' and (text() = 'Our Story' or . = 'Our Story')]</value>
      <webElementGuid>4e7c7166-e1ee-4094-9599-2c9f79a2a3ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
