<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>905e9b8d-aac4-4072-aaf6-4585a92fb593</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Daphne Koller: What we're learning from online education&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cascade-slider']/div[3]/div/div/div/p/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>36d3ab0c-ce0a-4fe3-bfe1-8d3cf2711510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>96748f34-c6bb-4da7-b8ab-c1fc7ae0d21d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>RSA ANIMATE: Changing Education Paradigms</value>
      <webElementGuid>6764fba3-d179-4a09-b53f-0b3c89b8e5c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.youtube.com/embed/zDZFcDGpL4U?feature=oembed</value>
      <webElementGuid>d0de3165-9c84-4092-95f1-4689ccc54b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>095abc90-0229-4f0d-873e-d8617e0d3121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>281</value>
      <webElementGuid>e63efc96-b973-46fc-b027-e751b98b5cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>99d14392-eadc-479d-a797-fc3cbc2220f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>cc35c657-b84b-46f6-bad9-d583b6f5e7c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cascade-slider&quot;)/div[@class=&quot;cascade-slider_slides&quot;]/div[@class=&quot;cascade-slider_item now&quot;]/div[@class=&quot;video-container&quot;]/div[@class=&quot;image-container&quot;]/p[1]/iframe[1]</value>
      <webElementGuid>1b73a67b-2600-4405-b9fd-22814141f919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture</value>
      <webElementGuid>7b56dc51-d953-4253-80f2-efeade15716c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cascade-slider']/div[4]/div/div/div/p/iframe</value>
      <webElementGuid>dc979849-70ea-4c1f-ad39-ef63f001ab83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/p/iframe</value>
      <webElementGuid>54d45976-952a-46d8-adf9-3a76282ce58f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'RSA ANIMATE: Changing Education Paradigms' and @src = 'https://www.youtube.com/embed/zDZFcDGpL4U?feature=oembed']</value>
      <webElementGuid>14b7373d-e1c4-4282-82a5-748f88c7c8a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cascade-slider']/div[3]/div/div/div/p/iframe</value>
      <webElementGuid>5e6bf55a-6a42-4fe7-8377-4de68456a08f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/p/iframe</value>
      <webElementGuid>4a42c766-ed08-45df-ac71-3ca81ce79dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = concat(&quot;Daphne Koller: What we&quot; , &quot;'&quot; , &quot;re learning from online education&quot;) and @src = 'https://embed.ted.com/talks/daphne_koller_what_we_re_learning_from_online_education']</value>
      <webElementGuid>b6e16c74-370f-4add-a9a0-621beb62c547</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
