<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Benefits_semester-icon</name>
   <tag></tag>
   <elementGuidId>5cc27ec4-f7de-45f4-9319-2acb261c323d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.semester-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'http://earthwp.magicmindtechnologies.com/dominion-latest-wp/wp-content/themes/dominionprep/assets/images/Icon-accl-learning.svg')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1d42bc37-b9e8-4845-bdf1-46bd788af5fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>semester-icon</value>
      <webElementGuid>9199d96c-70cc-4da7-b837-6373a05f6916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://earthwp.magicmindtechnologies.com/dominion-latest-wp/wp-content/themes/dominionprep/assets/images/Icon-accl-learning.svg</value>
      <webElementGuid>e442db4a-54d5-43ca-8e50-e7a9cf35e6cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;key-benefits&quot;]/div[@class=&quot;container div-with-bar light-mode&quot;]/div[@class=&quot;row benefits-inner-div&quot;]/div[@class=&quot;col-lg-4 col-md-12 col-sm-12 semester-div&quot;]/img[@class=&quot;semester-icon&quot;]</value>
      <webElementGuid>cb98908c-ece5-4288-b8de-a31510426513</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://earthwp.magicmindtechnologies.com/dominion-latest-wp/wp-content/themes/dominionprep/assets/images/Icon-accl-learning.svg')]</value>
      <webElementGuid>af75c6fb-c22b-4721-8880-13519b05be5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/img</value>
      <webElementGuid>d7da4f63-fdf4-42e3-b6a2-410bd3cef7ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://earthwp.magicmindtechnologies.com/dominion-latest-wp/wp-content/themes/dominionprep/assets/images/Icon-accl-learning.svg']</value>
      <webElementGuid>385a56e4-4c55-475c-b263-6c804557e1b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
