<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_This field is required_wpcf7-form-control has-spinner wpcf7-submit</name>
   <tag></tag>
   <elementGuidId>aa426355-c44a-429f-81a5-de730f3ee222</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.wpcf7-form-control.has-spinner.wpcf7-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae803ce3-1883-487b-a427-486871526ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>59792899-7c90-445d-b77b-bc60f3aa8793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>5927125a-2b0c-4f06-b429-2f94deeb2082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpcf7-form-control has-spinner wpcf7-submit</value>
      <webElementGuid>1b3bb66e-454d-42ab-ab6d-e10a624b1662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpcf7-f6-o1&quot;)/form[@class=&quot;wpcf7-form init theme_0 errorMsgshow&quot;]/input[@class=&quot;wpcf7-form-control has-spinner wpcf7-submit&quot;]</value>
      <webElementGuid>d06cca1c-1e30-4d84-a3e9-697c383211ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Submit']</value>
      <webElementGuid>7ad338c9-763d-48d3-a64e-649cfe47e731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpcf7-f6-o1']/form/input</value>
      <webElementGuid>46b36225-76a6-4e7d-a599-34279906691d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>58ec88e8-57f3-48e2-9a12-b06b556c360c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>2532e320-500a-4bec-8efe-eaf37bd113d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
