<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_This field is required_wpcf7-form-control has-spinner wpcf7-submit</name>
   <tag></tag>
   <elementGuidId>fcce9881-fc2b-4a41-b86c-88195e88f216</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.wpcf7-form-control.has-spinner.wpcf7-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad30d57d-a533-44d0-8e95-97acc7f8db21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>58e9d477-4b13-410c-b9d4-6f5a240780e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>0c82be8a-bb74-425f-9771-3d8855ed5e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpcf7-form-control has-spinner wpcf7-submit</value>
      <webElementGuid>67fd8f91-a4a4-4c0f-a9a8-f8fdd36b2fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpcf7-f6-o1&quot;)/form[@class=&quot;wpcf7-form init theme_0 errorMsgshow&quot;]/input[@class=&quot;wpcf7-form-control has-spinner wpcf7-submit&quot;]</value>
      <webElementGuid>a8f4ffa4-6329-404b-aad4-0f39d78dd948</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Submit']</value>
      <webElementGuid>16f0b4ae-991d-4ed6-9143-54b2f5595be6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpcf7-f6-o1']/form/input</value>
      <webElementGuid>9b8c048b-a0a8-4d0f-ba5e-9995458255e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>58f31ee7-64e3-4d71-9792-5368233da747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>3c75c1ba-cdbd-4722-a1e7-6c15840959a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
